version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py importdatajson &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - celery_worker
      - celery_beat
      - redis

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A drone_dispatch worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis 
    environment:
      - SECRET_KEY=${SECRET_KEY}

  celery_beat:
    build: .
    command: celery -A drone_dispatch beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis  
    environment:
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data:
