# Generated by Django 5.0.6 on 2024-06-27 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(choices=[('LIGHTWEIGHT', 'Lightweight'), ('MIDDLEWEIGHT', 'Middleweight'), ('CRUISERWEIGHT', 'Cruiserweight'), ('HEAVYWEIGHT', 'Heavyweight')], max_length=20)),
                ('weight_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE', max_length=20)),
            ],
        ),
    ]
