# Generated by Django 5.0.6 on 2024-06-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='medications/')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='dispatch.drone')),
            ],
        ),
    ]
