# Generated by Django 5.0.6 on 2024-06-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='DroneBatteryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.FloatField()),
                ('task_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry_duration_minutes', models.IntegerField(default=5)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.drone')),
            ],
            options={
                'verbose_name_plural': 'Drone Battery Audits',
            },
        ),
    ]
